export const dbDataTemplates = {
  CLINIC_QUERY: `<CLINIC_QUERY>
<QUERY_INFO>
    <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
</QUERY_INFO>
</CLINIC_QUERY>`,
  MOTCONSU_QUERY: `<MOTCONSU_QUERY>
<QUERY_INFO>
  <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
  <PID>%mmk%</PID>
<MOTCONSU_ID>%motconsuId%</MOTCONSU_ID>
</QUERY_INFO>
</MOTCONSU_QUERY>`,
  PLANNING_PARAMS_QUERY: `<PLANNING_PARAMS_QUERY>
  <QUERY_INFO>
    <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
    <PL_PARAMS_ID>%plParamsId%</PL_PARAMS_ID>
    <WEB_ACCESS>1</WEB_ACCESS>
  </QUERY_INFO>
</PLANNING_PARAMS_QUERY>
  `,
  PLANNING_SUBJ_QUERY: `<PLANNING_SUBJ_QUERY>
  <QUERY_INFO>
    <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
    <PL_PARAMS_ID>%plParamsId%</PL_PARAMS_ID>
    <WEB_ACCESS_ONLY>1</WEB_ACCESS_ONLY>
  </QUERY_INFO>
</PLANNING_SUBJ_QUERY>`,
  PLANNING_EXAMS_QUERY: `<PLANNING_EXAMS_QUERY>
<QUERY_INFO>
  <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
  <PL_SUBJ_ID>%plSubjId%</PL_SUBJ_ID>
</QUERY_INFO>
</PLANNING_EXAMS_QUERY>`,
  PLANNING_DAY_PARAMS_QUERY: `<PLANNING_DAY_PARAMS_QUERY>
<QUERY_INFO>
  <CLINIC_CODE>%clinicCode%</CLINIC_CODE>
  <PL_PARAMS_ID>%plParamsId%</PL_PARAMS_ID>  
  <PL_SUBJ_ID>%plSubjId%</PL_SUBJ_ID>
  <PL_DATE>%plDate%</PL_DATE>
</QUERY_INFO>
</PLANNING_DAY_PARAMS_QUERY>`,
};